# Generated by Django 6.0.2 on 2026-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=65535, null=True, verbose_name='Description')),
                ('due', models.DateField(blank=True, null=True, verbose_name='Due Date')),
            ],
        ),
    ]
